### ISSUE TITLE
Request: select type of audio device

### ISSUE THREAD

**Issue by Tiavor** [DanStevens/AudioEndPointController#7]
It would be nice to have an input argument to be able to also list and set the recording devices

Also: this program doesn't set the default communication device (NAudio defines it as type 2) i.e. skype uses this as default output.

**Comment by DanStevens** [comment]
To be perfectly honest, I've lost interest in this particular project. Since Windows 10 it's a lot easier to switch audio devices through the task tray, which was the original reason why I was looking into an automated way of changing default audio device.

There's a few forks now, so it's possible someone else actively working on this.

**Comment by Tiavor** [comment]
ok. my original intention was to have a background task checking if anything changed and then revert it back to what was set before as windows 10 likes to change the audio settings from time to time. I got an answer to this problem in another forum: windows saves the audio device config per monitor setup. meaning that every time I add a new audio device or switch usb ports, I have to go through every possible configuration of my 3 monitors (theoretical 4) , as they turn off with screen saver sometimes and can reactivate in different order. then and only then windows keeps quiet and doesn't change the default audio device anymore, until the next device change.
